export const a = [
    { id: 1, name: 'Dragon Ball', image: 'b' },
    { id: 2, name: 'Demon Slayer', image: 'b' },
    { id: 3, name: 'One Piece', image: 'as' },
    { id: 4, name: 'Attack on Titan', image: 'asdas' },
    { id: 5, name: 'Pokemon', image: 'asadas' },
    { id: 6, name: 'Bleach', image: 'a' },
    { id: 7, name: 'Naruto', image: 'a' },
    { id: 8, name: 'Death Note', image: 'b' },
    { id: 9, name: 'Hunter x Hunter', image: 'v' },
    { id: 10, name: 'Jujutsu Kaisen', image: 'n' },
    { id: 11, name: 'Spy x Family', image: 'l' },
    { id: 12, name: 'Mashle: Magic and Muscles', image: 'b' },
    { id: 13, name: "Hell's Paradise", image: 'n' },
    { id: 14, name: 'Oshi no Ko', image: 'n' },
    { id: 15, name: 'Cyberpunk: Edgerunners', image: 'n' },
    { id: 16, name: 'Tokyo Revengers', image: 'l' },
    { id: 17, name: 'Tokyo Ghoul', image: 'n' },
    { id: 18, name: 'Baki Hanma', image: 'a' },
    { id: 19, name: 'Ragna Crimson', image: 'a' }
]